src/Entity/Objet.php
<?php

namespace App\Entity;

use Assert\Length;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ObjetRepository;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: ObjetRepository::class)]
#[UniqueEntity(fields: ['numSerie'], message: 'Un objet existe déjà avec ce numéro de Serie')]
class Objet
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
  
    private ?string $numSerie = null;

    


    #[ORM\Column(length: 255)]
    private ?string $etatUsure = null;

    #[ORM\Column(length: 255)]
    private ?string $categorie = null;

    #[ORM\Column(length: 255)]
    private ?string $disponibilite = 'Disponible'; 

    #[ORM\Column(length: 255)]
    private ?string $photo_url = null;

    #[Gedmo\Timestampable(on: "create")]
    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: false)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;



    public function __construct()
    {
        $this->createdAt = new \DateTime(); // Automatically set the creation date
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getNumSerie(): ?string
    {
        return $this->numSerie;
    }

    public function setNumSerie(string $numSerie): static
    {
        $this->numSerie = $numSerie;

        return $this;
    }
 

    public function getEtatUsure(): ?string
    {
        return $this->etatUsure;
    }

    public function setEtatUsure(string $etatUsure): static
    {
        $this->etatUsure = $etatUsure;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getDisponibilite(): ?string
    {
        return $this->disponibilite;
    }

    public function setDisponibilite(string $disponibilite): static
    {
        $this->disponibilite = $disponibilite;

        return $this;
    }

    public function getPhotoUrl(): ?string
    {
        return $this->photo_url;
    }

    public function setPhotoUrl(string $photo_url): static
    {
        $this->photo_url = $photo_url;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }


































}

src/Form/ObjetType.php
<?php
namespace App\Form;

use App\Entity\Objet;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class ObjetType extends AbstractType
{
public function buildForm(FormBuilderInterface $builder, array $options): void
{
$builder
    ->add('nom', TextType::class, [
    'label' => 'Nom Objet:',
    'attr' => ['class' => 'form-control'],
    'constraints' => [new NotBlank(['message' => 'Le nom ne peut pas être vide.'])]
    ])

    ->add('description', TextType::class, [
    'label' => 'Description:',
    'attr' => ['class' => 'form-control']
    ])

    ->add('num_serie', TextType::class, [
    'label' => 'Numéro de Série:',
    'attr' => ['class' => 'form-control'],
    'constraints' => [
    new NotBlank(['message' => 'Le numéro de série ne peut pas être vide.']),
    new Length(['min' => 5, 'max' => 40])
    ]
    ])

    ->add('etat_usure', TextType::class, [
    'label' => 'État Usure:',
    'attr' => ['class' => 'form-control']
    ])

    ->add('categorie', ChoiceType::class, [
    'label' => 'Catégorie:',
    'choices' => [
    'Sur Place' => 'Sur Place',
    'Pour Emprunt' => 'Pour Emprunt'
    ],
    'attr' => ['class' => 'form-control']
    ])

    ->add('disponibilite', ChoiceType::class, [
    'label' => 'Disponibilité:',
    'choices' => [
    'Disponible' => 'Disponible',
    'Réservé' => 'Réservé',
    'Endommagé' => 'Endommagé',
    'En réparation' => 'En réparation',
    'Perdu' => 'Perdu'
    ],
    'attr' => ['class' => 'form-control']
    ])

    ->add('photo_url', FileType::class, [
    'label' => 'Photo:',
    'mapped' => false, // non mappé car géré manuellement
    'required' => false, // pas obligatoire
    'constraints' => [
    new File([
   
    'mimeTypes' => ['image/jpeg', 'image/png'],
    'mimeTypesMessage' => 'Veuillez télécharger une image valide (JPEG/PNG).'
    ])
],
'attr' => ['class' => 'form-control']
]);

        // Event listener to handle unchanged fields
        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
        $objet = $event->getData();
        $form = $event->getForm();

        if ($objet && $objet->getPhotoUrl()) {
        $form->add('photo_url', FileType::class, [
        'label' => 'Changer la photo (laissez vide pour conserver l\'actuelle)',
        'mapped' => false,
        'required' => false, // Facultatif, si aucune nouvelle image n'est fournie
        'attr' => ['class' => 'form-control']
        ]);
        }
        });
}

public function configureOptions(OptionsResolver $resolver): void
{
$resolver->setDefaults([
'data_class' => Objet::class,
]);
}
}

src/Controller/ObjetController.php
<?php

namespace App\Controller;

use App\Entity\Objet;
use App\Form\ObjetType;
use App\Form\ObjetEditType;
use App\Repository\ObjetRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

#[Route('/admin')]
class ObjetController extends AbstractController
{
    #[Route('/ListObjets', name: 'app_objet', methods: ['GET'])]
    public function index(Request $request, ObjetRepository $objetRepository, PaginatorInterface $paginator): Response
    {
        $queryBuilder = $objetRepository->createQueryBuilder('o')
            ->orderBy('o.createdAt', 'DESC'); // Assurez-vous que 'createdAt' est la propriété de votre entité qui stocke la date de création
    
        $pagination = $paginator->paginate(
            $queryBuilder, 
            $request->query->getInt('page', 1), 
            6 
        );
    
        return $this->render('objet/index.html.twig', [
            'pagination' => $pagination,
        ]);
    }
    

     // Ajouter un nouveau objet
    #[Route('/nouveau/objet', name: 'app_objet_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager,SluggerInterface $slugger): Response
    {
        $objet = new Objet();
        $form = $this->createForm(ObjetType::class, $objet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

        /** @var UploadedFile $photoFile */
        $photoFile = $form->get('photo_url')->getData();

        if ($photoFile) {
            $originalFilename = pathinfo($photoFile->getClientOriginalName(), PATHINFO_FILENAME);
            $safeFilename = $slugger->slug($originalFilename);
            $newFilename = $safeFilename.'-'.uniqid().'.'.$photoFile->guessExtension();

            // Move the file to the directory where photos are stored
            try {
                $photoFile->move(
                    $this->getParameter('photos_directory'),
                    $newFilename
                );
            } catch (FileException $e) {
                // Handle the exception if something happens during file upload
                throw new \Exception('Échec du téléchargement du fichier: ' . $e->getMessage());
            }

            // Set the new filename in the entity
            $objet->setPhotoUrl($newFilename);
        }



            $entityManager->persist($objet);
            $entityManager->flush();

            return $this->redirectToRoute('app_objet', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('objet/new.html.twig', [
            'objet' => $objet,
            'form' => $form,
        ]);
    }

    //afficher les details d'un objet
    #[Route('/objet/detail/{id}', name: 'app_objet_detail', methods: ['GET'])]
    public function detail(Objet $objet): Response
    {
        return $this->render('objet/detail.html.twig', [
            'objet' => $objet,
        ]);
    }


    
    #[Route('/edit/objet/{id}', name: 'app_objet_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Objet $objet, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ObjetType::class, $objet);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            $photoFile = $form->get('photo_url')->getData(); // Nouveau fichier image
    
            if ($photoFile) {
                // Gérer l'upload de la nouvelle image (vous devrez stocker le fichier sur le serveur)
                $newFilename = uniqid().'.'.$photoFile->guessExtension();
    
                // Déplace le fichier vers le répertoire où les images sont stockées
                try {
                    $photoFile->move(
                        $this->getParameter('photos_directory'),
                        $newFilename
                    );
                    // Met à jour l'URL de la photo dans l'objet
                    $objet->setPhotoUrl($newFilename);
                } catch (FileException $e) {
                    // gérer les exceptions si nécessaire
                }
            }
    
            $entityManager->flush();
    
            return $this->redirectToRoute('app_objet', [], Response::HTTP_SEE_OTHER);
        }
    
        return $this->render('objet/edit.html.twig', [
            'objet' => $objet,
            'form' => $form,
        ]);
    }
    



    //supprimer un objet
    #[Route('/objet/{id}', name: 'app_objet_delete', methods: ['POST'])]
    public function delete(Request $request, Objet $objet, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$objet->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($objet);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_objet', [], Response::HTTP_SEE_OTHER);
    }
}

templates/objet/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail de l'objet
{% endblock %}

{% block body %}
	<div class="container my-5">
		<h2 class="text-center mb-4">{{ objet.nom }}</h2>

		<div class="row justify-content-center">
			<div class="col-md-8 col-lg-6">
				<div class="card shadow-sm border-light">
					<img src="{{ asset('/uploads/photos/' ~ objet.photoUrl) }}" class="card-img-top" alt="{{ objet.nom }}">

					<div class="card-body">
						<h5 class="card-title">Détails de l'objet</h5>

						<ul class="list-group list-group-flush">
							{% if objet.description is not empty %}
								<li class="list-group-item">
									<strong>Description :</strong>
									{{ objet.description }}
								</li>
							{% endif %}

							<li class="list-group-item">
								<strong>Numéro de série :</strong>
								{{ objet.numSerie }}
							</li>
							<li class="list-group-item">
								<strong>État d'usure :</strong>
								{{ objet.etatUsure }}
							</li>
							<li class="list-group-item">
								<strong>Catégorie :</strong>
								{{ objet.categorie }}
							</li>
							<li class="list-group-item">
								<strong>Disponibilité :</strong>
								{{ objet.disponibilite }}
							</li>
							<li class="list-group-item">
								<strong>Enregistré le :</strong>
								{{ objet.createdAt|date('d-M-Y à H:i:s') }}
							</li>
						</ul>
					</div>

					<div class="card-footer text-center">
						<a href="{{ path('app_objet') }}" class="btn btn-outline-dark me-2">Retour</a>
						<a href="{{ path('app_objet_edit', {'id': objet.id}) }}" class="btn btn-outline-primary me-2">Modifier</a>

						<form method="post" action="{{ path('app_objet_delete', {'id': objet.id}) }}" class="d-inline delete-form" data-objet="{{ objet.nom }}">
							<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ objet.id) }}">
							<button type="submit" class="btn btn-outline-danger">Supprimer</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block javascripts %}
	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
	<script>
		document.addEventListener('DOMContentLoaded', function () {
document.querySelectorAll('.delete-form').forEach(function (form) {
form.addEventListener('submit', function (event) {
event.preventDefault();
const objet = form.getAttribute('data-objet');

Swal.fire({
title: 'Êtes-vous sûr ?',
text: `Vous êtes sur le point de supprimer ${objet}. Cette action est irréversible !`,
icon: 'warning',
showCancelButton: true,
confirmButtonColor: '#3085d6',
cancelButtonColor: '#d33',
confirmButtonText: 'Oui, supprimer !',
cancelButtonText: 'Annuler'
}).then((result) => {
if (result.isConfirmed) {
form.submit();
}
});
});
});
});
	</script>
{% endblock %}

templates/objet/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Éditer l'Objet
{% endblock %}

{% block body %}
	<div class="container my-5">
		<h2 class="text-center mb-4">Éditer
			{{ objet.nom|capitalize }}</h2>

		<div class="row justify-content-center">
			<div class="col-lg-8 col-md-10 col-sm-12">
				<div class="card shadow-sm border-light">
					<div class="card-body">
						{{ form_start(form) }}

						<div class="mb-3">
							{{ form_widget(form) }}
						</div>

						<div class="d-flex justify-content-center">
							<button type="submit" class="btn btn-outline-primary">Enregistrer</button>&nbsp;&nbsp;
							<a href="{{ path('app_objet') }}" class="btn btn-outline-secondary">Retour</a>
						</div>

						{{ form_end(form) }}
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/objet/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des Objets
{% endblock %}

{% block body %}
	<div class="container mt-4">
		<h2 class="text-center mb-4">Gestion des Objets</h2>

		<div class="mb-3">
			<a href="{{ path('app_objet_new') }}" class="btn btn-outline-primary">
				<i class="bi bi-plus-circle me-2"></i>
				+ Nouveau Objet
			</a>
		</div>

		<div class="row">
			{% for objet in pagination.items %}
				<div class="col-lg-4 col-md-6 mb-4">
					<div class="card border-light shadow-sm">
						{% if objet.photoUrl %}
							<img src="{{ asset('/uploads/photos/' ~ objet.photoUrl) }}" class="card-img-top" alt="{{ objet.nom }}">
						{% endif %}


						<div class="card-body">
							<h5 class="card-title">{{ objet.nom }}</h5>
							<div class="d-flex align-items-center">
								<a href="{{ path('app_objet_detail', {'id': objet.id}) }}" class="btn btn-outline-warning">Détails</a>&nbsp;&nbsp;

								{% if is_granted('ROLE_USER') and not is_granted('ROLE_ADMIN') %}
									<a href="{{ path('app_reservation_new', {'id': objet.id}) }}" class="btn btn-success">Réserver</a>
								{% endif %}

								<form method="post" action="{{ path('app_objet_delete', {'id': objet.id}) }}" class="d-inline">
									<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ objet.id) }}">
									<button type="submit" class="btn btn-outline-danger">Supprimer</button>
								</form>
							</div>
						</div>


					</div>
				</div>
			{% else %}
				<div class="col-12">
					<div class="alert alert-info text-center">
						Aucun objet trouvé.
					</div>
				</div>
			{% endfor %}
		</div>

		<div class="d-flex justify-content-center mb-4">
			{{ knp_pagination_render(pagination) }}
		</div>
	</div>
{% endblock %}

templates/objet/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer un Nouvel Objet
{% endblock %}

{% block body %}
	<div class="container my-5">
		<h2 class="text-center mb-4">Créer un Nouvel Objet</h2>

		<div class="row justify-content-center">
			<div class="col-lg-8 col-md-10 col-sm-12">
				<div class="card shadow-sm border-light">
					<div class="card-body">
						{{ form_start(form) }}

						<div class="mb-3">
							{{ form_widget(form) }}
						</div>

						<div class="d-flex justify-content-center">
							<button type="submit" class="btn btn-outline-primary">Enregistrer</button>&nbsp;&nbsp;
							<a href="{{ path('app_objet') }}" class="btn btn-outline-secondary">Retour</a>
						</div>

						{{ form_end(form) }}
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}